name: CI/CD for Frontend

on:
  push:
    branches: [ staging, main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: 18

jobs:
  build-and-test:
    name: Build and Test Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build --if-present

  notify:
    name: Send Notifications
    needs: [build-and-test]
    runs-on: ubuntu-latest
    if: always() # Siempre se ejecuta, incluso si el job anterior falla
    steps:
      - name: Send Status Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Deploy Status: ${{ github.repository }} - ${{ needs.build-and-test.result }}"
          body: |
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Status: ${{ needs.build-and-test.result }}
            Commit: ${{ github.sha }}
            Author: ${{ github.actor }}
            
            View run details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          to: ${{ secrets.NOTIFY_EMAIL }}
          from: GitHub Actions Notifier

      - name: Notify Teams via Power Automate
        if: success() || failure() # Solo se ejecuta si el job anterior tuvo éxito o falló
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
                "repository": "${{ github.repository }}",
                "branch": "${{ github.ref_name }}",
                "status": "${{ needs.build-and-test.result }}",
                "author": "${{ github.actor }}",
                "run_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
              }' \
          "${{ secrets.TEAMS_WEBHOOK }}"